spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/account
    username: brryu
    password: brryu5000!
    hikari:
      auto-commit: false
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 60000
      maximum-pool-size: 10
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show-sql: true
        use_sql_comments: false
    open-in-view: false

logging:
  config: classpath:logback/logback-remote.xml
  file:
    path: ${user.home}/logs/account
    name: account.log