spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/account
    username: brryu
    password: brryu5000!
    hikari:
      auto-commit: false
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 60000
      maximum-pool-size: 10
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show-sql: true
        use_sql_comments: false
    open-in-view: false
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/account
    user: brryu
    password: brryu5000!
    encoding: UTF-8
    locations: classpath:db/migration
    table: flyway_schema_history
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    baseline-description: test
    baseline-on-migrate: true
    clean-disabled: true
    clean-on-validation-error: false
    installed-by: account
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(CAlWI1BeES7idnwqXcdC9C6RG6PAO+TZEJ5uwQYosjA=)
    password: ENC(WLvgCc4EKnQtsacTy0MdMB+3yKaDjGit7wTOTCPIEpI=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

logging:
  config: classpath:logback/logback-remote.xml
  file:
    path: ${user.home}/logs/account
    name: account.log

application:
  async-executor:
    core-pool-size: 10
    max-pool-size: 100
    queue-capacity: 10000
  mail:
    sender-mail-address: stg-no-reply@gmail.com