server:
  port: 8081
  servlet:
    context-path: /account
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: account
  profiles:
    active: local

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /account/swagger/v1/swagger.yml